### ISSUE TITLE
Publish to Composer

### ISSUE THREAD

**Issue by srsgores** [defenestrator/laravel5-couchdb#1]
Package is not available on composer:

> composer require defenestrator/laravel5-couchdb  
>   [InvalidArgumentException]  
>   Could not find package defenestrator/laravel5-couchdb at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by defenestrator** [comment]
I will update this and publish it, soon. Thank you.

**Comment by defenestrator** [comment]
published today
